# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftWeiBo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftWeiBo
pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.2.2'
pod 'SDWebImage', '~> 4.2.2'
pod 'SnapKit', '~> 3.2.0'

#  target 'SwiftWeiBoTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

#  target 'SwiftWeiBoUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
